// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package persistence

import (
	"context"
)

const findStateByEmail = `-- name: FindStateByEmail :one
SELECT email, state FROM conversation_state WHERE email = $1
`

func (q *Queries) FindStateByEmail(ctx context.Context, email string) (ConversationState, error) {
	row := q.db.QueryRowContext(ctx, findStateByEmail, email)
	var i ConversationState
	err := row.Scan(&i.Email, &i.State)
	return i, err
}

const updateState = `-- name: UpdateState :exec
INSERT INTO conversation_state (email, state)
VALUES ($1, $2)
ON CONFLICT (email) DO UPDATE SET
    state = EXCLUDED.state
`

type UpdateStateParams struct {
	Email string `json:"email"`
	State string `json:"state"`
}

func (q *Queries) UpsertState(ctx context.Context, arg UpdateStateParams) error {
	_, err := q.db.ExecContext(ctx, updateState, arg.Email, arg.State)
	return err
}
